name: Linting Pipeline

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Linting Tools
        run: npm install htmlhint stylelint --save-dev
      - name: Run HTMLHint
        run: npx htmlhint "**/*.html"
      - name: Run Stylelint
        run: npx stylelint "**/*.css"
